async function init() {
  // Load tile metadata (auto-generated by your workflow)
  // Use a relative URL so it works on GitHub Pages under /MMService/
  const indexUrl = "tiles/index.json";
  const res = await fetch(indexUrl, { cache: "no-store" });

  if (!res.ok) {
    throw new Error(`Failed to load ${indexUrl}: ${res.status} ${res.statusText}`);
  }

  const idx = await res.json();

  const TILE_SIZE = Number(idx.tileSize ?? 512);
  const minX = Number(idx.minX);
  const maxX = Number(idx.maxX);
  const minY = Number(idx.minY);
  const maxY = Number(idx.maxY);
  const version = String(idx.version ?? "1");

  if (
    !Number.isFinite(TILE_SIZE) ||
    !Number.isFinite(minX) || !Number.isFinite(maxX) ||
    !Number.isFinite(minY) || !Number.isFinite(maxY)
  ) {
    throw new Error(`Invalid tiles/index.json contents: ${JSON.stringify(idx)}`);
  }

  // Pixel bounds for CRS.Simple
  // Leaflet bounds order is: [[yMin, xMin], [yMax, xMax]]
  const pixelBounds = [
    [minY * TILE_SIZE, minX * TILE_SIZE],
    [(maxY + 1) * TILE_SIZE, (maxX + 1) * TILE_SIZE],
  ];

  // 1) Map init (flat coordinate system)
  const map = L.map("map", {
    crs: L.CRS.Simple,

    zoomControl: false,
    scrollWheelZoom: false,
    doubleClickZoom: false, // disables double tap to zoom on mobile too
    dragging: true,

    worldCopyJump: false,

    // Clamp panning to your tile rectangle
    maxBounds: pixelBounds,
    maxBoundsViscosity: 1.0,
  });

  // Start centered on your actual tile coverage
  map.fitBounds(pixelBounds);

  // 2) Custom tile layer:
  // You only have ONE native tile resolution, so we always request native tiles
  // and let Leaflet scale them to simulate zoom.
  const MocodoniaTileLayer = L.TileLayer.extend({
    getTileUrl: function (coords) {
      // Convert requested coords at zoom z back to native tile coords (z=0)
      const scale = Math.pow(2, coords.z);
      const x = Math.floor(coords.x / scale);
      const y = Math.floor(coords.y / scale);

      // Use a stable version string (commit SHA) so browsers can cache tiles
      return `tiles/${x},${y}.png?v=${encodeURIComponent(version)}`;
    },
  });

  // 3) Tile layer initialization
  new MocodoniaTileLayer("", {
    attribution: "MMService • Mocodonia",

    tileSize: TILE_SIZE,
    noWrap: true,
    bounds: pixelBounds,
    keepBuffer: 6,

    // "Fake zoom" range (tune to taste)
    minZoom: -3,
    maxZoom: 3,
    zoomSnap: 0.25,
    zoomDelta: 0.25,

    // We only have one native zoom level worth of tiles
    minNativeZoom: 0,
    maxNativeZoom: 0,
  }).addTo(map);

  // Optional: keep your original behavior (no zoom UI / wheel zoom).
  // If you later want zoom buttons, set zoomControl:true above or add L.control.zoom().
}

init().catch((err) => {
  console.error(err);
});
